name: flowder
description: Persistent file downloader manager, start, pause, resume, cancel your download.
version: 0.2.0
homepage: https://github.com/Crdzbird/flowder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0-beta7

dev_dependencies:
  flutter_test:
    sdk: flutter